const LAYOUT = [
  // Row 0 — Function row
  [
    { id: "esc",  label: "esc",  w: "w-[46px]" },
    { id: "f1",   top: "🔆", label: "F1",   w: "w-[38px]" },
    { id: "f2",   top: "☀️", label: "F2",   w: "w-[38px]" },
    { id: "f3",   top: "⊞",  label: "F3",   w: "w-[38px]" },
    { id: "f4",   top: "⌕",  label: "F4",   w: "w-[38px]" },
    { id: "f5",   top: "🎤", label: "F5",   w: "w-[38px]" },
    { id: "f6",   top: "🌙", label: "F6",   w: "w-[38px]" },
    { id: "f7",   top: "⏮", label: "F7",   w: "w-[38px]" },
    { id: "f8",   top: "⏯", label: "F8",   w: "w-[38px]" },
    { id: "f9",   top: "⏭", label: "F9",   w: "w-[38px]" },
    { id: "f10",  top: "🔇", label: "F10",  w: "w-[38px]" },
    { id: "f11",  top: "🔉", label: "F11",  w: "w-[38px]" },
    { id: "f12",  top: "🔊", label: "F12",  w: "w-[38px]" },
    { id: "touch", label: "⏻", w: "w-[38px]", accent: true },
  ],
  // Row 1 — Number row
  [
    { id: "grave", top: "~",  label: "`",   w: "w-[46px]" },
    { id: "1",     top: "!",  label: "1",   w: "w-[46px]" },
    { id: "2",     top: "@",  label: "2",   w: "w-[46px]" },
    { id: "3",     top: "#",  label: "3",   w: "w-[46px]" },
    { id: "4",     top: "$",  label: "4",   w: "w-[46px]" },
    { id: "5",     top: "%",  label: "5",   w: "w-[46px]" },
    { id: "6",     top: "^",  label: "6",   w: "w-[46px]" },
    { id: "7",     top: "&",  label: "7",   w: "w-[46px]" },
    { id: "8",     top: "*",  label: "8",   w: "w-[46px]" },
    { id: "9",     top: "(",  label: "9",   w: "w-[46px]" },
    { id: "0",     top: ")",  label: "0",   w: "w-[46px]" },
    { id: "minus", top: "_",  label: "-",   w: "w-[46px]" },
    { id: "equal", top: "+",  label: "=",   w: "w-[46px]" },
    { id: "bksp",  label: "⌫", w: "w-[72px]" },
  ],
  // Row 2 — QWERTY
  [
    { id: "tab", label: "⇥ tab", w: "w-[72px]" },
    { id: "q",   label: "Q",     w: "w-[46px]" },
    { id: "w",   label: "W",     w: "w-[46px]" },
    { id: "e",   label: "E",     w: "w-[46px]" },
    { id: "r",   label: "R",     w: "w-[46px]" },
    { id: "t",   label: "T",     w: "w-[46px]" },
    { id: "y",   label: "Y",     w: "w-[46px]" },
    { id: "u",   label: "U",     w: "w-[46px]" },
    { id: "i",   label: "I",     w: "w-[46px]" },
    { id: "o",   label: "O",     w: "w-[46px]" },
    { id: "p",   label: "P",     w: "w-[46px]" },
    { id: "lbr", top: "{", label: "[", w: "w-[46px]" },
    { id: "rbr", top: "}", label: "]", w: "w-[46px]" },
    { id: "bsl", top: "|", label: "\\", w: "w-[46px]" },
  ],
  // Row 3 — Home row
  [
    { id: "caps",   label: "⇪ caps lock", w: "w-[84px]" },
    { id: "a",      label: "A",  w: "w-[46px]" },
    { id: "s",      label: "S",  w: "w-[46px]" },
    { id: "d",      label: "D",  w: "w-[46px]" },
    { id: "f",      label: "F",  w: "w-[46px]" },
    { id: "g",      label: "G",  w: "w-[46px]" },
    { id: "h",      label: "H",  w: "w-[46px]" },
    { id: "j",      label: "J",  w: "w-[46px]" },
    { id: "k",      label: "K",  w: "w-[46px]" },
    { id: "l",      label: "L",  w: "w-[46px]" },
    { id: "semi",   top: ":", label: ";", w: "w-[46px]" },
    { id: "quote",  top: '"', label: "'", w: "w-[46px]" },
    { id: "enter",  label: "return ↵", w: "w-[84px]" },
  ],
  // Row 4 — Shift row
  [
    { id: "lshift", label: "⇧", w: "w-[112px]" },
    { id: "z",      label: "Z",  w: "w-[46px]" },
    { id: "x",      label: "X",  w: "w-[46px]" },
    { id: "c",      label: "C",  w: "w-[46px]" },
    { id: "v",      label: "V",  w: "w-[46px]" },
    { id: "b",      label: "B",  w: "w-[46px]" },
    { id: "n",      label: "N",  w: "w-[46px]" },
    { id: "m",      label: "M",  w: "w-[46px]" },
    { id: "comma",  top: "<", label: ",", w: "w-[46px]" },
    { id: "dot",    top: ">", label: ".", w: "w-[46px]" },
    { id: "slash",  top: "?", label: "/", w: "w-[46px]" },
    { id: "rshift", label: "⇧", w: "w-[112px]" },
  ],
  // Row 5 — Bottom row
  [
    { id: "fn",      label: "fn",      w: "w-[46px]" },
    { id: "ctrl",    label: "control", w: "w-[54px]" },
    { id: "lopt",    label: "⌥ option", w: "w-[60px]" },
    { id: "lcmd",    label: "⌘ command", w: "w-[84px]" },
    { id: "space",   label: "",        w: "w-[256px]", isSpace: true },
    { id: "rcmd",    label: "⌘ command", w: "w-[84px]" },
    { id: "ropt",    label: "⌥ option", w: "w-[60px]" },
    { id: "left",    label: "◀",       w: "w-[30px]", half: true },
    { id: "updown",  upLabel: "▲", downLabel: "▼", w: "w-[30px]", split: true },
    { id: "right",   label: "▶",       w: "w-[30px]", half: true },
  ],
];